version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.18.0-browsers
    working_directory: ~/twhelpwebsite
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      # build the application image
      - run: docker build -t $DOCKER_LOGIN/twhelp-website:latest .

      # deploy the image
      - run: docker push $DOCKER_LOGIN/twhelp-website:latest
workflows:
  version: 2
  deploy_prod:
    jobs:
      - build:
          context: TWHelp
          filters:
            branches:
              only:
                - master
